### ISSUE TITLE
Use rust style instead of old-fashioned loops

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#36]
New algorithms for polynomial multiplications and inverses were implemented using old-fashioned loops. The pros and cons of using this approach could lead to a long discussion. Being more pragmatic, we are primarily interested in performance, therefore if using the appropriate rust techniques leads to better performance, we must use it. Even if performance is same, we should opt for the rust style. 

- [ ] Benchmark and compare the practical effect of different possible refactorings.
- [ ] Decide for the best solution and apply it.

**Comment by teor2345** [comment]
Since we're still working on the initial implementation, I think this might be a `wontfix` for now?

**Comment by teor2345** [comment]
Usually this doesn't actually make a difference to the compiler. Loops and iterators optimise roughly the same.

If we find a hot method (#39), we can try refactorings there.
