### ISSUE TITLE
Implement the plaintext encoding

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#37]
Subtasks: 
- [x] Implement the encoding described in this Notion [page](https://www.notion.so/inversed/Polynomial-Encodings-for-FHE-Relative-Hamming-Comparison-3df0095d2ee9429794a6cdba5d986a96?pvs=4)
    - [x] #40
    - [x] Implement masked bit encoding
    - [x] #49
        - [x] Middle resolution
        - [x] High resolution

Optional:
- [ ] #50

**Comment by emmorais** [comment]
The only difference for ciphertext encoding is the Finite Field, then ideally we should be able to use this implementation also for the NTRU encoding, since the ciphertext is given just by one polynomial.

**Comment by bgillesp** [comment]
Following up on questions from @teor2345:
> - What are Non-interfering Two-polynomial Embeddings?
> - What is the Second Order Polynomial Encoding?
> - What are the parameters for low resolution? They don't seem to be in the report.

The Notion page that was linked above describing plaintext encodings is an [old version](https://www.notion.so/inversed/SI-NTRU-Masked-Bit-Vector-Encoding-Method-and-Relative-Hamming-Comparison-1740e33a0e864f6b86f677d0683834ba?pvs=4), and we should instead reference the [newer version](https://www.notion.so/inversed/Polynomial-Encodings-for-FHE-Relative-Hamming-Comparison-3df0095d2ee9429794a6cdba5d986a96?pvs=4) which describes the more efficient encoding   method included in the viability report.  In particular:
- The "Non-interfering Two-polynomial Embedding" component is no longer needed
- The "Second Order Polynomial Encoding" component is no longer needed

For the last point, the low-resolution parameters are not a priority right now based on the likely high-level roadmap -- the main function of a low-res encoding would be for a low-res to high-res iterated filter, which approach we are planning to skip in favor of a direct step up to the HNSW search algorithm.  The latter will most likely make use of a mid-res encoding scheme.

I'll update the main subtasks list for this issue to reflect these comments.

**Comment by teor2345** [comment]
The only task left here is “integrate encoding and encryption” (#89) so I’m going to close this ticket.
