### ISSUE TITLE
2.1.1. Implement homomorphic encryption algorithms 

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#38]
This is deliverable 1 in milestone 1 of phase 2.

Subtasks: 
- [x] Implement low-level polynomial operations
  - [x] #12
  - [x] #63 
- [x] #64
  - [ ] #70
  - [x] #72
  - [x] #73
  - [ ] #74
  - [ ] #77
- [x] #78
- [x] #95
- [ ] Decrypt homomorphic computation (decryption is specific to the homomorphic computation, it can't be used to decrypt original ciphertexts containing iris codes, since its key was modified, however is not hard to obtain the original private key from this special key, but maybe there is a way to explore this path and get closer to achieve key deletion).

**Comment by teor2345** [comment]
All the essential parts of this are done, or have other tickets.
