### ISSUE TITLE
2.1.4. Implement R-LWE plaintext polynomial encodings for medium and high resolution iris codes 

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#49]
This is deliverable 4 in milestone 1 of phase 2.

Polynomial encodings transforming low and high resolution iris codes to R-LWE plaintext polynomials.

- [x] https://github.com/Inversed-Tech/eyelid/issues/81
- [ ] https://github.com/Inversed-Tech/eyelid/issues/88
- [ ] https://github.com/Inversed-Tech/eyelid/issues/89

**Comment by teor2345** [comment]
The only task left here is #89, so I’m going to close this ticket.
