### ISSUE TITLE
Integrate encoding and encryption

### ISSUE THREAD

**Issue by naure** [Inversed-Tech/eyelid#89]
Implement a function using existing building blocks:
- [x] Encoded iris codes into polynomials (`encoded` module)
- [x] Encrypt the encoded polynomials
- [x] Multiply a code and a query
- [x] Decrypt the result including inner products
    - [x] Comment that making comparison private (#87) is a TODO 
- [x] Compare to threshold in plaintext

**Comment by teor2345** [comment]
This comment from Bryan about resolutions might be helpful here:
https://github.com/Inversed-Tech/eyelid/issues/37#issuecomment-2148045822
