### ISSUE TITLE
Decide how to configure plaintext and ciphertext parameters

### ISSUE THREAD

**Issue by emmorais** [Inversed-Tech/eyelid#90]
There are different ways to implement the configuration we need, as can be seen in this [discussion](https://github.com/Inversed-Tech/eyelid/pull/82#discussion_r1599846550).

For example, we could:
- manually configure two separate `PolyConf`s, and require their degrees to be equal, or
- we could define a degree and two coefficient types, and automatically create two `PolyConf`s from them.

The goal of this task is to analyze the nuances pointed out in this discussion a implement a solution. 

- [ ] define the best approach
- [ ] implement the new configuration
- [ ] refactor the code

**Comment by teor2345** [comment]
We effectively decided this over PRs #97 and #98.
